name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Compress binary
        run: |
          cd bin
          tar -czf generate-mac.tar.gz generate
          shasum -a 256 generate-mac.tar.gz > generate-mac.tar.gz.sha256

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/generate-mac.tar.gz
            bin/generate-mac.tar.gz.sha256
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
